version: "3"
services:
  api:
    container_name: recipe_api
    build: api
    ports:
      - 3000:3000
    depends_on:
      - db
    env_file:
      - development.env
    networks:
      - recipe-network
  db:
    container_name: recipe_db
    build: db
    env_file:
      - development.env
    networks:
      - recipe-network

networks:
  recipe-network:
    external: true